version: "3.8"

services:
  app:
    build:
      context: .
    environment:
      - CUSTOMCONNSTR_ApplicationDbContext=Host=postgres;Database=postgres;Username=postgres;Password=postgres
      - Authentication__Secret=QmEQ1YOH4cKAjLVCopJuBsz8qi7xopJYTWqgK2I8Obd3wJUCIzdw89UXiiQ78JkF
      - Elastic__Url=http://elastic:9200
      - Urls=http://*:8088
      - Serilog__WriteTo__0__Name=Console
      - External__Masterdata__BaseUrl=https://my-directus
      - External__Masterdata__GetPart=/items/parts?fields=no,name,uom_id.*
      - External__Masterdata__GetWarehouse=/items/warehouse_locations?fields=code,name,description
      - External__Masterdata__SecretToken=bcbac640-7e16-4662-aafe-33ad54aa2f61
      - Authentication__Worker__ApiKey=5186695d-f405-4457-a1cb-6359a784b96c
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      # - elastic
  postgres:
    image: debezium/example-postgres:1.7
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    # command:
    #   - "postgres"
    #   - "-c"
    #   - "wal_level=logical"
  # elastic:
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.2'
  #         #memory: 50M
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200